#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpfAppCBADoc
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CBADocentes")]
	public partial class DataClassesDocentesBDDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertAula(Aula instance);
    partial void UpdateAula(Aula instance);
    partial void DeleteAula(Aula instance);
    partial void InsertUsuario(Usuario instance);
    partial void UpdateUsuario(Usuario instance);
    partial void DeleteUsuario(Usuario instance);
    partial void InsertBeca(Beca instance);
    partial void UpdateBeca(Beca instance);
    partial void DeleteBeca(Beca instance);
    partial void InsertBimestre(Bimestre instance);
    partial void UpdateBimestre(Bimestre instance);
    partial void DeleteBimestre(Bimestre instance);
    partial void InsertCurso(Curso instance);
    partial void UpdateCurso(Curso instance);
    partial void DeleteCurso(Curso instance);
    partial void InsertEstadoAula(EstadoAula instance);
    partial void UpdateEstadoAula(EstadoAula instance);
    partial void DeleteEstadoAula(EstadoAula instance);
    partial void InsertEstadoPago(EstadoPago instance);
    partial void UpdateEstadoPago(EstadoPago instance);
    partial void DeleteEstadoPago(EstadoPago instance);
    partial void InsertEstudianteInscrito(EstudianteInscrito instance);
    partial void UpdateEstudianteInscrito(EstudianteInscrito instance);
    partial void DeleteEstudianteInscrito(EstudianteInscrito instance);
    partial void InsertHorario(Horario instance);
    partial void UpdateHorario(Horario instance);
    partial void DeleteHorario(Horario instance);
    partial void InsertLibro(Libro instance);
    partial void UpdateLibro(Libro instance);
    partial void DeleteLibro(Libro instance);
    partial void InsertModulo(Modulo instance);
    partial void UpdateModulo(Modulo instance);
    partial void DeleteModulo(Modulo instance);
    partial void InsertModuloImpartido(ModuloImpartido instance);
    partial void UpdateModuloImpartido(ModuloImpartido instance);
    partial void DeleteModuloImpartido(ModuloImpartido instance);
    partial void InsertNotaCurso(NotaCurso instance);
    partial void UpdateNotaCurso(NotaCurso instance);
    partial void DeleteNotaCurso(NotaCurso instance);
    partial void InsertPago(Pago instance);
    partial void UpdatePago(Pago instance);
    partial void DeletePago(Pago instance);
    partial void InsertPersona(Persona instance);
    partial void UpdatePersona(Persona instance);
    partial void DeletePersona(Persona instance);
    partial void InsertRol(Rol instance);
    partial void UpdateRol(Rol instance);
    partial void DeleteRol(Rol instance);
    partial void InsertSucursal(Sucursal instance);
    partial void UpdateSucursal(Sucursal instance);
    partial void DeleteSucursal(Sucursal instance);
    #endregion
		
		public DataClassesDocentesBDDataContext() : 
				base(global::wpfAppCBADoc.Properties.Settings.Default.CBADocentesConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDocentesBDDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDocentesBDDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDocentesBDDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDocentesBDDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Aula> Aula
		{
			get
			{
				return this.GetTable<Aula>();
			}
		}
		
		public System.Data.Linq.Table<Usuario> Usuario
		{
			get
			{
				return this.GetTable<Usuario>();
			}
		}
		
		public System.Data.Linq.Table<Beca> Beca
		{
			get
			{
				return this.GetTable<Beca>();
			}
		}
		
		public System.Data.Linq.Table<Bimestre> Bimestre
		{
			get
			{
				return this.GetTable<Bimestre>();
			}
		}
		
		public System.Data.Linq.Table<Curso> Curso
		{
			get
			{
				return this.GetTable<Curso>();
			}
		}
		
		public System.Data.Linq.Table<EstadoAula> EstadoAula
		{
			get
			{
				return this.GetTable<EstadoAula>();
			}
		}
		
		public System.Data.Linq.Table<EstadoPago> EstadoPago
		{
			get
			{
				return this.GetTable<EstadoPago>();
			}
		}
		
		public System.Data.Linq.Table<EstudianteInscrito> EstudianteInscrito
		{
			get
			{
				return this.GetTable<EstudianteInscrito>();
			}
		}
		
		public System.Data.Linq.Table<Horario> Horario
		{
			get
			{
				return this.GetTable<Horario>();
			}
		}
		
		public System.Data.Linq.Table<Libro> Libro
		{
			get
			{
				return this.GetTable<Libro>();
			}
		}
		
		public System.Data.Linq.Table<Modulo> Modulo
		{
			get
			{
				return this.GetTable<Modulo>();
			}
		}
		
		public System.Data.Linq.Table<ModuloImpartido> ModuloImpartido
		{
			get
			{
				return this.GetTable<ModuloImpartido>();
			}
		}
		
		public System.Data.Linq.Table<NotaCurso> NotaCurso
		{
			get
			{
				return this.GetTable<NotaCurso>();
			}
		}
		
		public System.Data.Linq.Table<Pago> Pago
		{
			get
			{
				return this.GetTable<Pago>();
			}
		}
		
		public System.Data.Linq.Table<Persona> Persona
		{
			get
			{
				return this.GetTable<Persona>();
			}
		}
		
		public System.Data.Linq.Table<Rol> Rol
		{
			get
			{
				return this.GetTable<Rol>();
			}
		}
		
		public System.Data.Linq.Table<Sucursal> Sucursal
		{
			get
			{
				return this.GetTable<Sucursal>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Aula")]
	public partial class Aula : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdAula;
		
		private string _NumeroAula;
		
		private int _Capacidad;
		
		private int _IdSucursal;
		
		private int _IdEstadoA;
		
		private EntitySet<ModuloImpartido> _ModuloImpartido;
		
		private EntityRef<EstadoAula> _EstadoAula;
		
		private EntityRef<Sucursal> _Sucursal;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdAulaChanging(int value);
    partial void OnIdAulaChanged();
    partial void OnNumeroAulaChanging(string value);
    partial void OnNumeroAulaChanged();
    partial void OnCapacidadChanging(int value);
    partial void OnCapacidadChanged();
    partial void OnIdSucursalChanging(int value);
    partial void OnIdSucursalChanged();
    partial void OnIdEstadoAChanging(int value);
    partial void OnIdEstadoAChanged();
    #endregion
		
		public Aula()
		{
			this._ModuloImpartido = new EntitySet<ModuloImpartido>(new Action<ModuloImpartido>(this.attach_ModuloImpartido), new Action<ModuloImpartido>(this.detach_ModuloImpartido));
			this._EstadoAula = default(EntityRef<EstadoAula>);
			this._Sucursal = default(EntityRef<Sucursal>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdAula", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdAula
		{
			get
			{
				return this._IdAula;
			}
			set
			{
				if ((this._IdAula != value))
				{
					this.OnIdAulaChanging(value);
					this.SendPropertyChanging();
					this._IdAula = value;
					this.SendPropertyChanged("IdAula");
					this.OnIdAulaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroAula", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NumeroAula
		{
			get
			{
				return this._NumeroAula;
			}
			set
			{
				if ((this._NumeroAula != value))
				{
					this.OnNumeroAulaChanging(value);
					this.SendPropertyChanging();
					this._NumeroAula = value;
					this.SendPropertyChanged("NumeroAula");
					this.OnNumeroAulaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Capacidad", DbType="Int NOT NULL")]
		public int Capacidad
		{
			get
			{
				return this._Capacidad;
			}
			set
			{
				if ((this._Capacidad != value))
				{
					this.OnCapacidadChanging(value);
					this.SendPropertyChanging();
					this._Capacidad = value;
					this.SendPropertyChanged("Capacidad");
					this.OnCapacidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdSucursal", DbType="Int NOT NULL")]
		public int IdSucursal
		{
			get
			{
				return this._IdSucursal;
			}
			set
			{
				if ((this._IdSucursal != value))
				{
					if (this._Sucursal.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdSucursalChanging(value);
					this.SendPropertyChanging();
					this._IdSucursal = value;
					this.SendPropertyChanged("IdSucursal");
					this.OnIdSucursalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEstadoA", DbType="Int NOT NULL")]
		public int IdEstadoA
		{
			get
			{
				return this._IdEstadoA;
			}
			set
			{
				if ((this._IdEstadoA != value))
				{
					if (this._EstadoAula.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdEstadoAChanging(value);
					this.SendPropertyChanging();
					this._IdEstadoA = value;
					this.SendPropertyChanged("IdEstadoA");
					this.OnIdEstadoAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Aula_ModuloImpartido", Storage="_ModuloImpartido", ThisKey="IdAula", OtherKey="IdAula")]
		public EntitySet<ModuloImpartido> ModuloImpartido
		{
			get
			{
				return this._ModuloImpartido;
			}
			set
			{
				this._ModuloImpartido.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="EstadoAula_Aula", Storage="_EstadoAula", ThisKey="IdEstadoA", OtherKey="IdEstadoA", IsForeignKey=true)]
		public EstadoAula EstadoAula
		{
			get
			{
				return this._EstadoAula.Entity;
			}
			set
			{
				EstadoAula previousValue = this._EstadoAula.Entity;
				if (((previousValue != value) 
							|| (this._EstadoAula.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._EstadoAula.Entity = null;
						previousValue.Aula.Remove(this);
					}
					this._EstadoAula.Entity = value;
					if ((value != null))
					{
						value.Aula.Add(this);
						this._IdEstadoA = value.IdEstadoA;
					}
					else
					{
						this._IdEstadoA = default(int);
					}
					this.SendPropertyChanged("EstadoAula");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Sucursal_Aula", Storage="_Sucursal", ThisKey="IdSucursal", OtherKey="IdSucursal", IsForeignKey=true)]
		public Sucursal Sucursal
		{
			get
			{
				return this._Sucursal.Entity;
			}
			set
			{
				Sucursal previousValue = this._Sucursal.Entity;
				if (((previousValue != value) 
							|| (this._Sucursal.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Sucursal.Entity = null;
						previousValue.Aula.Remove(this);
					}
					this._Sucursal.Entity = value;
					if ((value != null))
					{
						value.Aula.Add(this);
						this._IdSucursal = value.IdSucursal;
					}
					else
					{
						this._IdSucursal = default(int);
					}
					this.SendPropertyChanged("Sucursal");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ModuloImpartido(ModuloImpartido entity)
		{
			this.SendPropertyChanging();
			entity.Aula = this;
		}
		
		private void detach_ModuloImpartido(ModuloImpartido entity)
		{
			this.SendPropertyChanging();
			entity.Aula = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuario")]
	public partial class Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdUsuario;
		
		private string _Correo;
		
		private string _Contrasenia;
		
		private int _IdRol;
		
		private int _IdPersona;
		
		private EntityRef<Persona> _Persona;
		
		private EntityRef<Rol> _Rol;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdUsuarioChanging(int value);
    partial void OnIdUsuarioChanged();
    partial void OnCorreoChanging(string value);
    partial void OnCorreoChanged();
    partial void OnContraseniaChanging(string value);
    partial void OnContraseniaChanged();
    partial void OnIdRolChanging(int value);
    partial void OnIdRolChanged();
    partial void OnIdPersonaChanging(int value);
    partial void OnIdPersonaChanged();
    #endregion
		
		public Usuario()
		{
			this._Persona = default(EntityRef<Persona>);
			this._Rol = default(EntityRef<Rol>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					this.OnIdUsuarioChanging(value);
					this.SendPropertyChanging();
					this._IdUsuario = value;
					this.SendPropertyChanged("IdUsuario");
					this.OnIdUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo", DbType="NVarChar(70) NOT NULL", CanBeNull=false)]
		public string Correo
		{
			get
			{
				return this._Correo;
			}
			set
			{
				if ((this._Correo != value))
				{
					this.OnCorreoChanging(value);
					this.SendPropertyChanging();
					this._Correo = value;
					this.SendPropertyChanged("Correo");
					this.OnCorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contrasenia", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Contrasenia
		{
			get
			{
				return this._Contrasenia;
			}
			set
			{
				if ((this._Contrasenia != value))
				{
					this.OnContraseniaChanging(value);
					this.SendPropertyChanging();
					this._Contrasenia = value;
					this.SendPropertyChanged("Contrasenia");
					this.OnContraseniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdRol", DbType="Int NOT NULL")]
		public int IdRol
		{
			get
			{
				return this._IdRol;
			}
			set
			{
				if ((this._IdRol != value))
				{
					if (this._Rol.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdRolChanging(value);
					this.SendPropertyChanging();
					this._IdRol = value;
					this.SendPropertyChanged("IdRol");
					this.OnIdRolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPersona", DbType="Int NOT NULL")]
		public int IdPersona
		{
			get
			{
				return this._IdPersona;
			}
			set
			{
				if ((this._IdPersona != value))
				{
					if (this._Persona.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdPersonaChanging(value);
					this.SendPropertyChanging();
					this._IdPersona = value;
					this.SendPropertyChanged("IdPersona");
					this.OnIdPersonaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Persona_Usuario", Storage="_Persona", ThisKey="IdPersona", OtherKey="IdPersona", IsForeignKey=true)]
		public Persona Persona
		{
			get
			{
				return this._Persona.Entity;
			}
			set
			{
				Persona previousValue = this._Persona.Entity;
				if (((previousValue != value) 
							|| (this._Persona.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Persona.Entity = null;
						previousValue.Usuario.Remove(this);
					}
					this._Persona.Entity = value;
					if ((value != null))
					{
						value.Usuario.Add(this);
						this._IdPersona = value.IdPersona;
					}
					else
					{
						this._IdPersona = default(int);
					}
					this.SendPropertyChanged("Persona");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Rol_Usuario", Storage="_Rol", ThisKey="IdRol", OtherKey="IdRol", IsForeignKey=true)]
		public Rol Rol
		{
			get
			{
				return this._Rol.Entity;
			}
			set
			{
				Rol previousValue = this._Rol.Entity;
				if (((previousValue != value) 
							|| (this._Rol.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Rol.Entity = null;
						previousValue.Usuario.Remove(this);
					}
					this._Rol.Entity = value;
					if ((value != null))
					{
						value.Usuario.Add(this);
						this._IdRol = value.IdRol;
					}
					else
					{
						this._IdRol = default(int);
					}
					this.SendPropertyChanged("Rol");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Beca")]
	public partial class Beca : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdBeca;
		
		private string _Nombre;
		
		private decimal _Descuento;
		
		private EntitySet<Persona> _Persona;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdBecaChanging(int value);
    partial void OnIdBecaChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnDescuentoChanging(decimal value);
    partial void OnDescuentoChanged();
    #endregion
		
		public Beca()
		{
			this._Persona = new EntitySet<Persona>(new Action<Persona>(this.attach_Persona), new Action<Persona>(this.detach_Persona));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdBeca", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdBeca
		{
			get
			{
				return this._IdBeca;
			}
			set
			{
				if ((this._IdBeca != value))
				{
					this.OnIdBecaChanging(value);
					this.SendPropertyChanging();
					this._IdBeca = value;
					this.SendPropertyChanged("IdBeca");
					this.OnIdBecaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descuento", DbType="Decimal(8,2) NOT NULL")]
		public decimal Descuento
		{
			get
			{
				return this._Descuento;
			}
			set
			{
				if ((this._Descuento != value))
				{
					this.OnDescuentoChanging(value);
					this.SendPropertyChanging();
					this._Descuento = value;
					this.SendPropertyChanged("Descuento");
					this.OnDescuentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Beca_Persona", Storage="_Persona", ThisKey="IdBeca", OtherKey="IdBeca")]
		public EntitySet<Persona> Persona
		{
			get
			{
				return this._Persona;
			}
			set
			{
				this._Persona.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Persona(Persona entity)
		{
			this.SendPropertyChanging();
			entity.Beca = this;
		}
		
		private void detach_Persona(Persona entity)
		{
			this.SendPropertyChanging();
			entity.Beca = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Bimestre")]
	public partial class Bimestre : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdBimestre;
		
		private System.DateTime _FechaInicio;
		
		private System.DateTime _FechaFin;
		
		private string _Gestion;
		
		private EntitySet<ModuloImpartido> _ModuloImpartido;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdBimestreChanging(int value);
    partial void OnIdBimestreChanged();
    partial void OnFechaInicioChanging(System.DateTime value);
    partial void OnFechaInicioChanged();
    partial void OnFechaFinChanging(System.DateTime value);
    partial void OnFechaFinChanged();
    partial void OnGestionChanging(string value);
    partial void OnGestionChanged();
    #endregion
		
		public Bimestre()
		{
			this._ModuloImpartido = new EntitySet<ModuloImpartido>(new Action<ModuloImpartido>(this.attach_ModuloImpartido), new Action<ModuloImpartido>(this.detach_ModuloImpartido));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdBimestre", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdBimestre
		{
			get
			{
				return this._IdBimestre;
			}
			set
			{
				if ((this._IdBimestre != value))
				{
					this.OnIdBimestreChanging(value);
					this.SendPropertyChanging();
					this._IdBimestre = value;
					this.SendPropertyChanged("IdBimestre");
					this.OnIdBimestreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaInicio", DbType="Date NOT NULL")]
		public System.DateTime FechaInicio
		{
			get
			{
				return this._FechaInicio;
			}
			set
			{
				if ((this._FechaInicio != value))
				{
					this.OnFechaInicioChanging(value);
					this.SendPropertyChanging();
					this._FechaInicio = value;
					this.SendPropertyChanged("FechaInicio");
					this.OnFechaInicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaFin", DbType="Date NOT NULL")]
		public System.DateTime FechaFin
		{
			get
			{
				return this._FechaFin;
			}
			set
			{
				if ((this._FechaFin != value))
				{
					this.OnFechaFinChanging(value);
					this.SendPropertyChanging();
					this._FechaFin = value;
					this.SendPropertyChanged("FechaFin");
					this.OnFechaFinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gestion", DbType="NVarChar(4) NOT NULL", CanBeNull=false)]
		public string Gestion
		{
			get
			{
				return this._Gestion;
			}
			set
			{
				if ((this._Gestion != value))
				{
					this.OnGestionChanging(value);
					this.SendPropertyChanging();
					this._Gestion = value;
					this.SendPropertyChanged("Gestion");
					this.OnGestionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Bimestre_ModuloImpartido", Storage="_ModuloImpartido", ThisKey="IdBimestre", OtherKey="IdBimestre")]
		public EntitySet<ModuloImpartido> ModuloImpartido
		{
			get
			{
				return this._ModuloImpartido;
			}
			set
			{
				this._ModuloImpartido.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ModuloImpartido(ModuloImpartido entity)
		{
			this.SendPropertyChanging();
			entity.Bimestre = this;
		}
		
		private void detach_ModuloImpartido(ModuloImpartido entity)
		{
			this.SendPropertyChanging();
			entity.Bimestre = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Curso")]
	public partial class Curso : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdCurso;
		
		private string _Nombre;
		
		private EntitySet<Libro> _Libro;
		
		private EntitySet<Modulo> _Modulo;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdCursoChanging(int value);
    partial void OnIdCursoChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    #endregion
		
		public Curso()
		{
			this._Libro = new EntitySet<Libro>(new Action<Libro>(this.attach_Libro), new Action<Libro>(this.detach_Libro));
			this._Modulo = new EntitySet<Modulo>(new Action<Modulo>(this.attach_Modulo), new Action<Modulo>(this.detach_Modulo));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCurso", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdCurso
		{
			get
			{
				return this._IdCurso;
			}
			set
			{
				if ((this._IdCurso != value))
				{
					this.OnIdCursoChanging(value);
					this.SendPropertyChanging();
					this._IdCurso = value;
					this.SendPropertyChanged("IdCurso");
					this.OnIdCursoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Curso_Libro", Storage="_Libro", ThisKey="IdCurso", OtherKey="IdCurso")]
		public EntitySet<Libro> Libro
		{
			get
			{
				return this._Libro;
			}
			set
			{
				this._Libro.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Curso_Modulo", Storage="_Modulo", ThisKey="IdCurso", OtherKey="IdCurso")]
		public EntitySet<Modulo> Modulo
		{
			get
			{
				return this._Modulo;
			}
			set
			{
				this._Modulo.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Libro(Libro entity)
		{
			this.SendPropertyChanging();
			entity.Curso = this;
		}
		
		private void detach_Libro(Libro entity)
		{
			this.SendPropertyChanging();
			entity.Curso = null;
		}
		
		private void attach_Modulo(Modulo entity)
		{
			this.SendPropertyChanging();
			entity.Curso = this;
		}
		
		private void detach_Modulo(Modulo entity)
		{
			this.SendPropertyChanging();
			entity.Curso = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EstadoAula")]
	public partial class EstadoAula : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdEstadoA;
		
		private string _Estado;
		
		private EntitySet<Aula> _Aula;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdEstadoAChanging(int value);
    partial void OnIdEstadoAChanged();
    partial void OnEstadoChanging(string value);
    partial void OnEstadoChanged();
    #endregion
		
		public EstadoAula()
		{
			this._Aula = new EntitySet<Aula>(new Action<Aula>(this.attach_Aula), new Action<Aula>(this.detach_Aula));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEstadoA", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdEstadoA
		{
			get
			{
				return this._IdEstadoA;
			}
			set
			{
				if ((this._IdEstadoA != value))
				{
					this.OnIdEstadoAChanging(value);
					this.SendPropertyChanging();
					this._IdEstadoA = value;
					this.SendPropertyChanged("IdEstadoA");
					this.OnIdEstadoAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="EstadoAula_Aula", Storage="_Aula", ThisKey="IdEstadoA", OtherKey="IdEstadoA")]
		public EntitySet<Aula> Aula
		{
			get
			{
				return this._Aula;
			}
			set
			{
				this._Aula.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Aula(Aula entity)
		{
			this.SendPropertyChanging();
			entity.EstadoAula = this;
		}
		
		private void detach_Aula(Aula entity)
		{
			this.SendPropertyChanging();
			entity.EstadoAula = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EstadoPago")]
	public partial class EstadoPago : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdEstadoP;
		
		private string _Estado;
		
		private EntitySet<Pago> _Pago;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdEstadoPChanging(int value);
    partial void OnIdEstadoPChanged();
    partial void OnEstadoChanging(string value);
    partial void OnEstadoChanged();
    #endregion
		
		public EstadoPago()
		{
			this._Pago = new EntitySet<Pago>(new Action<Pago>(this.attach_Pago), new Action<Pago>(this.detach_Pago));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEstadoP", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdEstadoP
		{
			get
			{
				return this._IdEstadoP;
			}
			set
			{
				if ((this._IdEstadoP != value))
				{
					this.OnIdEstadoPChanging(value);
					this.SendPropertyChanging();
					this._IdEstadoP = value;
					this.SendPropertyChanged("IdEstadoP");
					this.OnIdEstadoPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="NVarChar(50)")]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="EstadoPago_Pago", Storage="_Pago", ThisKey="IdEstadoP", OtherKey="IdEstadoP")]
		public EntitySet<Pago> Pago
		{
			get
			{
				return this._Pago;
			}
			set
			{
				this._Pago.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Pago(Pago entity)
		{
			this.SendPropertyChanging();
			entity.EstadoPago = this;
		}
		
		private void detach_Pago(Pago entity)
		{
			this.SendPropertyChanging();
			entity.EstadoPago = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EstudianteInscrito")]
	public partial class EstudianteInscrito : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdEstInsc;
		
		private int _IdModuloImp;
		
		private int _IdPersona;
		
		private System.DateTime _Fecha_Inscripcion;
		
		private EntitySet<NotaCurso> _NotaCurso;
		
		private EntitySet<Pago> _Pago;
		
		private EntityRef<ModuloImpartido> _ModuloImpartido;
		
		private EntityRef<Persona> _Persona;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdEstInscChanging(int value);
    partial void OnIdEstInscChanged();
    partial void OnIdModuloImpChanging(int value);
    partial void OnIdModuloImpChanged();
    partial void OnIdPersonaChanging(int value);
    partial void OnIdPersonaChanged();
    partial void OnFecha_InscripcionChanging(System.DateTime value);
    partial void OnFecha_InscripcionChanged();
    #endregion
		
		public EstudianteInscrito()
		{
			this._NotaCurso = new EntitySet<NotaCurso>(new Action<NotaCurso>(this.attach_NotaCurso), new Action<NotaCurso>(this.detach_NotaCurso));
			this._Pago = new EntitySet<Pago>(new Action<Pago>(this.attach_Pago), new Action<Pago>(this.detach_Pago));
			this._ModuloImpartido = default(EntityRef<ModuloImpartido>);
			this._Persona = default(EntityRef<Persona>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEstInsc", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdEstInsc
		{
			get
			{
				return this._IdEstInsc;
			}
			set
			{
				if ((this._IdEstInsc != value))
				{
					this.OnIdEstInscChanging(value);
					this.SendPropertyChanging();
					this._IdEstInsc = value;
					this.SendPropertyChanged("IdEstInsc");
					this.OnIdEstInscChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdModuloImp", DbType="Int NOT NULL")]
		public int IdModuloImp
		{
			get
			{
				return this._IdModuloImp;
			}
			set
			{
				if ((this._IdModuloImp != value))
				{
					if (this._ModuloImpartido.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdModuloImpChanging(value);
					this.SendPropertyChanging();
					this._IdModuloImp = value;
					this.SendPropertyChanged("IdModuloImp");
					this.OnIdModuloImpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPersona", DbType="Int NOT NULL")]
		public int IdPersona
		{
			get
			{
				return this._IdPersona;
			}
			set
			{
				if ((this._IdPersona != value))
				{
					if (this._Persona.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdPersonaChanging(value);
					this.SendPropertyChanging();
					this._IdPersona = value;
					this.SendPropertyChanged("IdPersona");
					this.OnIdPersonaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Fecha Inscripcion]", Storage="_Fecha_Inscripcion", DbType="Date NOT NULL")]
		public System.DateTime Fecha_Inscripcion
		{
			get
			{
				return this._Fecha_Inscripcion;
			}
			set
			{
				if ((this._Fecha_Inscripcion != value))
				{
					this.OnFecha_InscripcionChanging(value);
					this.SendPropertyChanging();
					this._Fecha_Inscripcion = value;
					this.SendPropertyChanged("Fecha_Inscripcion");
					this.OnFecha_InscripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="EstudianteInscrito_NotaCurso", Storage="_NotaCurso", ThisKey="IdEstInsc", OtherKey="IdEstInsc")]
		public EntitySet<NotaCurso> NotaCurso
		{
			get
			{
				return this._NotaCurso;
			}
			set
			{
				this._NotaCurso.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="EstudianteInscrito_Pago", Storage="_Pago", ThisKey="IdEstInsc", OtherKey="IdEstInsc")]
		public EntitySet<Pago> Pago
		{
			get
			{
				return this._Pago;
			}
			set
			{
				this._Pago.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ModuloImpartido_EstudianteInscrito", Storage="_ModuloImpartido", ThisKey="IdModuloImp", OtherKey="IdModuloImp", IsForeignKey=true)]
		public ModuloImpartido ModuloImpartido
		{
			get
			{
				return this._ModuloImpartido.Entity;
			}
			set
			{
				ModuloImpartido previousValue = this._ModuloImpartido.Entity;
				if (((previousValue != value) 
							|| (this._ModuloImpartido.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ModuloImpartido.Entity = null;
						previousValue.EstudianteInscrito.Remove(this);
					}
					this._ModuloImpartido.Entity = value;
					if ((value != null))
					{
						value.EstudianteInscrito.Add(this);
						this._IdModuloImp = value.IdModuloImp;
					}
					else
					{
						this._IdModuloImp = default(int);
					}
					this.SendPropertyChanged("ModuloImpartido");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Persona_EstudianteInscrito", Storage="_Persona", ThisKey="IdPersona", OtherKey="IdPersona", IsForeignKey=true)]
		public Persona Persona
		{
			get
			{
				return this._Persona.Entity;
			}
			set
			{
				Persona previousValue = this._Persona.Entity;
				if (((previousValue != value) 
							|| (this._Persona.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Persona.Entity = null;
						previousValue.EstudianteInscrito.Remove(this);
					}
					this._Persona.Entity = value;
					if ((value != null))
					{
						value.EstudianteInscrito.Add(this);
						this._IdPersona = value.IdPersona;
					}
					else
					{
						this._IdPersona = default(int);
					}
					this.SendPropertyChanged("Persona");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NotaCurso(NotaCurso entity)
		{
			this.SendPropertyChanging();
			entity.EstudianteInscrito = this;
		}
		
		private void detach_NotaCurso(NotaCurso entity)
		{
			this.SendPropertyChanging();
			entity.EstudianteInscrito = null;
		}
		
		private void attach_Pago(Pago entity)
		{
			this.SendPropertyChanging();
			entity.EstudianteInscrito = this;
		}
		
		private void detach_Pago(Pago entity)
		{
			this.SendPropertyChanging();
			entity.EstudianteInscrito = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Horario")]
	public partial class Horario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdHorario;
		
		private System.DateTime _HoraInicio;
		
		private System.DateTime _HoraFinal;
		
		private EntitySet<ModuloImpartido> _ModuloImpartido;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdHorarioChanging(int value);
    partial void OnIdHorarioChanged();
    partial void OnHoraInicioChanging(System.DateTime value);
    partial void OnHoraInicioChanged();
    partial void OnHoraFinalChanging(System.DateTime value);
    partial void OnHoraFinalChanged();
    #endregion
		
		public Horario()
		{
			this._ModuloImpartido = new EntitySet<ModuloImpartido>(new Action<ModuloImpartido>(this.attach_ModuloImpartido), new Action<ModuloImpartido>(this.detach_ModuloImpartido));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdHorario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdHorario
		{
			get
			{
				return this._IdHorario;
			}
			set
			{
				if ((this._IdHorario != value))
				{
					this.OnIdHorarioChanging(value);
					this.SendPropertyChanging();
					this._IdHorario = value;
					this.SendPropertyChanged("IdHorario");
					this.OnIdHorarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoraInicio", DbType="DateTime NOT NULL")]
		public System.DateTime HoraInicio
		{
			get
			{
				return this._HoraInicio;
			}
			set
			{
				if ((this._HoraInicio != value))
				{
					this.OnHoraInicioChanging(value);
					this.SendPropertyChanging();
					this._HoraInicio = value;
					this.SendPropertyChanged("HoraInicio");
					this.OnHoraInicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoraFinal", DbType="DateTime NOT NULL")]
		public System.DateTime HoraFinal
		{
			get
			{
				return this._HoraFinal;
			}
			set
			{
				if ((this._HoraFinal != value))
				{
					this.OnHoraFinalChanging(value);
					this.SendPropertyChanging();
					this._HoraFinal = value;
					this.SendPropertyChanged("HoraFinal");
					this.OnHoraFinalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Horario_ModuloImpartido", Storage="_ModuloImpartido", ThisKey="IdHorario", OtherKey="IdHorario")]
		public EntitySet<ModuloImpartido> ModuloImpartido
		{
			get
			{
				return this._ModuloImpartido;
			}
			set
			{
				this._ModuloImpartido.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ModuloImpartido(ModuloImpartido entity)
		{
			this.SendPropertyChanging();
			entity.Horario = this;
		}
		
		private void detach_ModuloImpartido(ModuloImpartido entity)
		{
			this.SendPropertyChanging();
			entity.Horario = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Libro")]
	public partial class Libro : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdLibro;
		
		private string _ISBN;
		
		private string _Nombre;
		
		private string _Descripcion;
		
		private decimal _Costo;
		
		private System.Nullable<int> _IdCurso;
		
		private EntityRef<Curso> _Curso;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdLibroChanging(int value);
    partial void OnIdLibroChanged();
    partial void OnISBNChanging(string value);
    partial void OnISBNChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    partial void OnCostoChanging(decimal value);
    partial void OnCostoChanged();
    partial void OnIdCursoChanging(System.Nullable<int> value);
    partial void OnIdCursoChanged();
    #endregion
		
		public Libro()
		{
			this._Curso = default(EntityRef<Curso>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdLibro", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdLibro
		{
			get
			{
				return this._IdLibro;
			}
			set
			{
				if ((this._IdLibro != value))
				{
					this.OnIdLibroChanging(value);
					this.SendPropertyChanging();
					this._IdLibro = value;
					this.SendPropertyChanged("IdLibro");
					this.OnIdLibroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISBN", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ISBN
		{
			get
			{
				return this._ISBN;
			}
			set
			{
				if ((this._ISBN != value))
				{
					this.OnISBNChanging(value);
					this.SendPropertyChanging();
					this._ISBN = value;
					this.SendPropertyChanged("ISBN");
					this.OnISBNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Costo", DbType="Decimal(8,2) NOT NULL")]
		public decimal Costo
		{
			get
			{
				return this._Costo;
			}
			set
			{
				if ((this._Costo != value))
				{
					this.OnCostoChanging(value);
					this.SendPropertyChanging();
					this._Costo = value;
					this.SendPropertyChanged("Costo");
					this.OnCostoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCurso", DbType="Int")]
		public System.Nullable<int> IdCurso
		{
			get
			{
				return this._IdCurso;
			}
			set
			{
				if ((this._IdCurso != value))
				{
					if (this._Curso.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdCursoChanging(value);
					this.SendPropertyChanging();
					this._IdCurso = value;
					this.SendPropertyChanged("IdCurso");
					this.OnIdCursoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Curso_Libro", Storage="_Curso", ThisKey="IdCurso", OtherKey="IdCurso", IsForeignKey=true)]
		public Curso Curso
		{
			get
			{
				return this._Curso.Entity;
			}
			set
			{
				Curso previousValue = this._Curso.Entity;
				if (((previousValue != value) 
							|| (this._Curso.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Curso.Entity = null;
						previousValue.Libro.Remove(this);
					}
					this._Curso.Entity = value;
					if ((value != null))
					{
						value.Libro.Add(this);
						this._IdCurso = value.IdCurso;
					}
					else
					{
						this._IdCurso = default(Nullable<int>);
					}
					this.SendPropertyChanged("Curso");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Modulo")]
	public partial class Modulo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdModulo;
		
		private string _Nombre;
		
		private int _IdCurso;
		
		private EntitySet<ModuloImpartido> _ModuloImpartido;
		
		private EntityRef<Curso> _Curso;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdModuloChanging(int value);
    partial void OnIdModuloChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnIdCursoChanging(int value);
    partial void OnIdCursoChanged();
    #endregion
		
		public Modulo()
		{
			this._ModuloImpartido = new EntitySet<ModuloImpartido>(new Action<ModuloImpartido>(this.attach_ModuloImpartido), new Action<ModuloImpartido>(this.detach_ModuloImpartido));
			this._Curso = default(EntityRef<Curso>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdModulo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdModulo
		{
			get
			{
				return this._IdModulo;
			}
			set
			{
				if ((this._IdModulo != value))
				{
					this.OnIdModuloChanging(value);
					this.SendPropertyChanging();
					this._IdModulo = value;
					this.SendPropertyChanged("IdModulo");
					this.OnIdModuloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCurso", DbType="Int NOT NULL")]
		public int IdCurso
		{
			get
			{
				return this._IdCurso;
			}
			set
			{
				if ((this._IdCurso != value))
				{
					if (this._Curso.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdCursoChanging(value);
					this.SendPropertyChanging();
					this._IdCurso = value;
					this.SendPropertyChanged("IdCurso");
					this.OnIdCursoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Modulo_ModuloImpartido", Storage="_ModuloImpartido", ThisKey="IdModulo", OtherKey="IdModulo")]
		public EntitySet<ModuloImpartido> ModuloImpartido
		{
			get
			{
				return this._ModuloImpartido;
			}
			set
			{
				this._ModuloImpartido.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Curso_Modulo", Storage="_Curso", ThisKey="IdCurso", OtherKey="IdCurso", IsForeignKey=true)]
		public Curso Curso
		{
			get
			{
				return this._Curso.Entity;
			}
			set
			{
				Curso previousValue = this._Curso.Entity;
				if (((previousValue != value) 
							|| (this._Curso.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Curso.Entity = null;
						previousValue.Modulo.Remove(this);
					}
					this._Curso.Entity = value;
					if ((value != null))
					{
						value.Modulo.Add(this);
						this._IdCurso = value.IdCurso;
					}
					else
					{
						this._IdCurso = default(int);
					}
					this.SendPropertyChanged("Curso");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ModuloImpartido(ModuloImpartido entity)
		{
			this.SendPropertyChanging();
			entity.Modulo = this;
		}
		
		private void detach_ModuloImpartido(ModuloImpartido entity)
		{
			this.SendPropertyChanging();
			entity.Modulo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ModuloImpartido")]
	public partial class ModuloImpartido : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdModuloImp;
		
		private int _IdModulo;
		
		private int _IdAula;
		
		private int _IdPersona;
		
		private int _IdHorario;
		
		private int _IdBimestre;
		
		private EntitySet<EstudianteInscrito> _EstudianteInscrito;
		
		private EntityRef<Aula> _Aula;
		
		private EntityRef<Bimestre> _Bimestre;
		
		private EntityRef<Horario> _Horario;
		
		private EntityRef<Modulo> _Modulo;
		
		private EntityRef<Persona> _Persona;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdModuloImpChanging(int value);
    partial void OnIdModuloImpChanged();
    partial void OnIdModuloChanging(int value);
    partial void OnIdModuloChanged();
    partial void OnIdAulaChanging(int value);
    partial void OnIdAulaChanged();
    partial void OnIdPersonaChanging(int value);
    partial void OnIdPersonaChanged();
    partial void OnIdHorarioChanging(int value);
    partial void OnIdHorarioChanged();
    partial void OnIdBimestreChanging(int value);
    partial void OnIdBimestreChanged();
    #endregion
		
		public ModuloImpartido()
		{
			this._EstudianteInscrito = new EntitySet<EstudianteInscrito>(new Action<EstudianteInscrito>(this.attach_EstudianteInscrito), new Action<EstudianteInscrito>(this.detach_EstudianteInscrito));
			this._Aula = default(EntityRef<Aula>);
			this._Bimestre = default(EntityRef<Bimestre>);
			this._Horario = default(EntityRef<Horario>);
			this._Modulo = default(EntityRef<Modulo>);
			this._Persona = default(EntityRef<Persona>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdModuloImp", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdModuloImp
		{
			get
			{
				return this._IdModuloImp;
			}
			set
			{
				if ((this._IdModuloImp != value))
				{
					this.OnIdModuloImpChanging(value);
					this.SendPropertyChanging();
					this._IdModuloImp = value;
					this.SendPropertyChanged("IdModuloImp");
					this.OnIdModuloImpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdModulo", DbType="Int NOT NULL")]
		public int IdModulo
		{
			get
			{
				return this._IdModulo;
			}
			set
			{
				if ((this._IdModulo != value))
				{
					if (this._Modulo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdModuloChanging(value);
					this.SendPropertyChanging();
					this._IdModulo = value;
					this.SendPropertyChanged("IdModulo");
					this.OnIdModuloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdAula", DbType="Int NOT NULL")]
		public int IdAula
		{
			get
			{
				return this._IdAula;
			}
			set
			{
				if ((this._IdAula != value))
				{
					if (this._Aula.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdAulaChanging(value);
					this.SendPropertyChanging();
					this._IdAula = value;
					this.SendPropertyChanged("IdAula");
					this.OnIdAulaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPersona", DbType="Int NOT NULL")]
		public int IdPersona
		{
			get
			{
				return this._IdPersona;
			}
			set
			{
				if ((this._IdPersona != value))
				{
					if (this._Persona.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdPersonaChanging(value);
					this.SendPropertyChanging();
					this._IdPersona = value;
					this.SendPropertyChanged("IdPersona");
					this.OnIdPersonaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdHorario", DbType="Int NOT NULL")]
		public int IdHorario
		{
			get
			{
				return this._IdHorario;
			}
			set
			{
				if ((this._IdHorario != value))
				{
					if (this._Horario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdHorarioChanging(value);
					this.SendPropertyChanging();
					this._IdHorario = value;
					this.SendPropertyChanged("IdHorario");
					this.OnIdHorarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdBimestre", DbType="Int NOT NULL")]
		public int IdBimestre
		{
			get
			{
				return this._IdBimestre;
			}
			set
			{
				if ((this._IdBimestre != value))
				{
					if (this._Bimestre.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdBimestreChanging(value);
					this.SendPropertyChanging();
					this._IdBimestre = value;
					this.SendPropertyChanged("IdBimestre");
					this.OnIdBimestreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ModuloImpartido_EstudianteInscrito", Storage="_EstudianteInscrito", ThisKey="IdModuloImp", OtherKey="IdModuloImp")]
		public EntitySet<EstudianteInscrito> EstudianteInscrito
		{
			get
			{
				return this._EstudianteInscrito;
			}
			set
			{
				this._EstudianteInscrito.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Aula_ModuloImpartido", Storage="_Aula", ThisKey="IdAula", OtherKey="IdAula", IsForeignKey=true)]
		public Aula Aula
		{
			get
			{
				return this._Aula.Entity;
			}
			set
			{
				Aula previousValue = this._Aula.Entity;
				if (((previousValue != value) 
							|| (this._Aula.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Aula.Entity = null;
						previousValue.ModuloImpartido.Remove(this);
					}
					this._Aula.Entity = value;
					if ((value != null))
					{
						value.ModuloImpartido.Add(this);
						this._IdAula = value.IdAula;
					}
					else
					{
						this._IdAula = default(int);
					}
					this.SendPropertyChanged("Aula");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Bimestre_ModuloImpartido", Storage="_Bimestre", ThisKey="IdBimestre", OtherKey="IdBimestre", IsForeignKey=true)]
		public Bimestre Bimestre
		{
			get
			{
				return this._Bimestre.Entity;
			}
			set
			{
				Bimestre previousValue = this._Bimestre.Entity;
				if (((previousValue != value) 
							|| (this._Bimestre.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Bimestre.Entity = null;
						previousValue.ModuloImpartido.Remove(this);
					}
					this._Bimestre.Entity = value;
					if ((value != null))
					{
						value.ModuloImpartido.Add(this);
						this._IdBimestre = value.IdBimestre;
					}
					else
					{
						this._IdBimestre = default(int);
					}
					this.SendPropertyChanged("Bimestre");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Horario_ModuloImpartido", Storage="_Horario", ThisKey="IdHorario", OtherKey="IdHorario", IsForeignKey=true)]
		public Horario Horario
		{
			get
			{
				return this._Horario.Entity;
			}
			set
			{
				Horario previousValue = this._Horario.Entity;
				if (((previousValue != value) 
							|| (this._Horario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Horario.Entity = null;
						previousValue.ModuloImpartido.Remove(this);
					}
					this._Horario.Entity = value;
					if ((value != null))
					{
						value.ModuloImpartido.Add(this);
						this._IdHorario = value.IdHorario;
					}
					else
					{
						this._IdHorario = default(int);
					}
					this.SendPropertyChanged("Horario");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Modulo_ModuloImpartido", Storage="_Modulo", ThisKey="IdModulo", OtherKey="IdModulo", IsForeignKey=true)]
		public Modulo Modulo
		{
			get
			{
				return this._Modulo.Entity;
			}
			set
			{
				Modulo previousValue = this._Modulo.Entity;
				if (((previousValue != value) 
							|| (this._Modulo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Modulo.Entity = null;
						previousValue.ModuloImpartido.Remove(this);
					}
					this._Modulo.Entity = value;
					if ((value != null))
					{
						value.ModuloImpartido.Add(this);
						this._IdModulo = value.IdModulo;
					}
					else
					{
						this._IdModulo = default(int);
					}
					this.SendPropertyChanged("Modulo");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Persona_ModuloImpartido", Storage="_Persona", ThisKey="IdPersona", OtherKey="IdPersona", IsForeignKey=true)]
		public Persona Persona
		{
			get
			{
				return this._Persona.Entity;
			}
			set
			{
				Persona previousValue = this._Persona.Entity;
				if (((previousValue != value) 
							|| (this._Persona.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Persona.Entity = null;
						previousValue.ModuloImpartido.Remove(this);
					}
					this._Persona.Entity = value;
					if ((value != null))
					{
						value.ModuloImpartido.Add(this);
						this._IdPersona = value.IdPersona;
					}
					else
					{
						this._IdPersona = default(int);
					}
					this.SendPropertyChanged("Persona");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_EstudianteInscrito(EstudianteInscrito entity)
		{
			this.SendPropertyChanging();
			entity.ModuloImpartido = this;
		}
		
		private void detach_EstudianteInscrito(EstudianteInscrito entity)
		{
			this.SendPropertyChanging();
			entity.ModuloImpartido = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NotaCurso")]
	public partial class NotaCurso : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdNota;
		
		private decimal _NotaListening;
		
		private decimal _NotaWritting;
		
		private decimal _NotaReading;
		
		private decimal _NotaSpeaking;
		
		private System.Nullable<int> _IdEstInsc;
		
		private EntityRef<EstudianteInscrito> _EstudianteInscrito;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdNotaChanging(int value);
    partial void OnIdNotaChanged();
    partial void OnNotaListeningChanging(decimal value);
    partial void OnNotaListeningChanged();
    partial void OnNotaWrittingChanging(decimal value);
    partial void OnNotaWrittingChanged();
    partial void OnNotaReadingChanging(decimal value);
    partial void OnNotaReadingChanged();
    partial void OnNotaSpeakingChanging(decimal value);
    partial void OnNotaSpeakingChanged();
    partial void OnIdEstInscChanging(System.Nullable<int> value);
    partial void OnIdEstInscChanged();
    #endregion
		
		public NotaCurso()
		{
			this._EstudianteInscrito = default(EntityRef<EstudianteInscrito>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdNota", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdNota
		{
			get
			{
				return this._IdNota;
			}
			set
			{
				if ((this._IdNota != value))
				{
					this.OnIdNotaChanging(value);
					this.SendPropertyChanging();
					this._IdNota = value;
					this.SendPropertyChanged("IdNota");
					this.OnIdNotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NotaListening", DbType="Decimal(3,2) NOT NULL")]
		public decimal NotaListening
		{
			get
			{
				return this._NotaListening;
			}
			set
			{
				if ((this._NotaListening != value))
				{
					this.OnNotaListeningChanging(value);
					this.SendPropertyChanging();
					this._NotaListening = value;
					this.SendPropertyChanged("NotaListening");
					this.OnNotaListeningChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NotaWritting", DbType="Decimal(3,2) NOT NULL")]
		public decimal NotaWritting
		{
			get
			{
				return this._NotaWritting;
			}
			set
			{
				if ((this._NotaWritting != value))
				{
					this.OnNotaWrittingChanging(value);
					this.SendPropertyChanging();
					this._NotaWritting = value;
					this.SendPropertyChanged("NotaWritting");
					this.OnNotaWrittingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NotaReading", DbType="Decimal(3,2) NOT NULL")]
		public decimal NotaReading
		{
			get
			{
				return this._NotaReading;
			}
			set
			{
				if ((this._NotaReading != value))
				{
					this.OnNotaReadingChanging(value);
					this.SendPropertyChanging();
					this._NotaReading = value;
					this.SendPropertyChanged("NotaReading");
					this.OnNotaReadingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NotaSpeaking", DbType="Decimal(3,2) NOT NULL")]
		public decimal NotaSpeaking
		{
			get
			{
				return this._NotaSpeaking;
			}
			set
			{
				if ((this._NotaSpeaking != value))
				{
					this.OnNotaSpeakingChanging(value);
					this.SendPropertyChanging();
					this._NotaSpeaking = value;
					this.SendPropertyChanged("NotaSpeaking");
					this.OnNotaSpeakingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEstInsc", DbType="Int")]
		public System.Nullable<int> IdEstInsc
		{
			get
			{
				return this._IdEstInsc;
			}
			set
			{
				if ((this._IdEstInsc != value))
				{
					if (this._EstudianteInscrito.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdEstInscChanging(value);
					this.SendPropertyChanging();
					this._IdEstInsc = value;
					this.SendPropertyChanged("IdEstInsc");
					this.OnIdEstInscChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="EstudianteInscrito_NotaCurso", Storage="_EstudianteInscrito", ThisKey="IdEstInsc", OtherKey="IdEstInsc", IsForeignKey=true)]
		public EstudianteInscrito EstudianteInscrito
		{
			get
			{
				return this._EstudianteInscrito.Entity;
			}
			set
			{
				EstudianteInscrito previousValue = this._EstudianteInscrito.Entity;
				if (((previousValue != value) 
							|| (this._EstudianteInscrito.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._EstudianteInscrito.Entity = null;
						previousValue.NotaCurso.Remove(this);
					}
					this._EstudianteInscrito.Entity = value;
					if ((value != null))
					{
						value.NotaCurso.Add(this);
						this._IdEstInsc = value.IdEstInsc;
					}
					else
					{
						this._IdEstInsc = default(Nullable<int>);
					}
					this.SendPropertyChanged("EstudianteInscrito");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Pago")]
	public partial class Pago : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdPago;
		
		private decimal _Monto;
		
		private System.DateTime _FechaSugerida;
		
		private string _TipoPago;
		
		private int _IdEstadoP;
		
		private int _IdEstInsc;
		
		private EntityRef<EstadoPago> _EstadoPago;
		
		private EntityRef<EstudianteInscrito> _EstudianteInscrito;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdPagoChanging(int value);
    partial void OnIdPagoChanged();
    partial void OnMontoChanging(decimal value);
    partial void OnMontoChanged();
    partial void OnFechaSugeridaChanging(System.DateTime value);
    partial void OnFechaSugeridaChanged();
    partial void OnTipoPagoChanging(string value);
    partial void OnTipoPagoChanged();
    partial void OnIdEstadoPChanging(int value);
    partial void OnIdEstadoPChanged();
    partial void OnIdEstInscChanging(int value);
    partial void OnIdEstInscChanged();
    #endregion
		
		public Pago()
		{
			this._EstadoPago = default(EntityRef<EstadoPago>);
			this._EstudianteInscrito = default(EntityRef<EstudianteInscrito>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPago", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdPago
		{
			get
			{
				return this._IdPago;
			}
			set
			{
				if ((this._IdPago != value))
				{
					this.OnIdPagoChanging(value);
					this.SendPropertyChanging();
					this._IdPago = value;
					this.SendPropertyChanged("IdPago");
					this.OnIdPagoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Monto", DbType="Decimal(3,2) NOT NULL")]
		public decimal Monto
		{
			get
			{
				return this._Monto;
			}
			set
			{
				if ((this._Monto != value))
				{
					this.OnMontoChanging(value);
					this.SendPropertyChanging();
					this._Monto = value;
					this.SendPropertyChanged("Monto");
					this.OnMontoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaSugerida", DbType="Date NOT NULL")]
		public System.DateTime FechaSugerida
		{
			get
			{
				return this._FechaSugerida;
			}
			set
			{
				if ((this._FechaSugerida != value))
				{
					this.OnFechaSugeridaChanging(value);
					this.SendPropertyChanging();
					this._FechaSugerida = value;
					this.SendPropertyChanged("FechaSugerida");
					this.OnFechaSugeridaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoPago", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TipoPago
		{
			get
			{
				return this._TipoPago;
			}
			set
			{
				if ((this._TipoPago != value))
				{
					this.OnTipoPagoChanging(value);
					this.SendPropertyChanging();
					this._TipoPago = value;
					this.SendPropertyChanged("TipoPago");
					this.OnTipoPagoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEstadoP", DbType="Int NOT NULL")]
		public int IdEstadoP
		{
			get
			{
				return this._IdEstadoP;
			}
			set
			{
				if ((this._IdEstadoP != value))
				{
					if (this._EstadoPago.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdEstadoPChanging(value);
					this.SendPropertyChanging();
					this._IdEstadoP = value;
					this.SendPropertyChanged("IdEstadoP");
					this.OnIdEstadoPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEstInsc", DbType="Int NOT NULL")]
		public int IdEstInsc
		{
			get
			{
				return this._IdEstInsc;
			}
			set
			{
				if ((this._IdEstInsc != value))
				{
					if (this._EstudianteInscrito.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdEstInscChanging(value);
					this.SendPropertyChanging();
					this._IdEstInsc = value;
					this.SendPropertyChanged("IdEstInsc");
					this.OnIdEstInscChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="EstadoPago_Pago", Storage="_EstadoPago", ThisKey="IdEstadoP", OtherKey="IdEstadoP", IsForeignKey=true)]
		public EstadoPago EstadoPago
		{
			get
			{
				return this._EstadoPago.Entity;
			}
			set
			{
				EstadoPago previousValue = this._EstadoPago.Entity;
				if (((previousValue != value) 
							|| (this._EstadoPago.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._EstadoPago.Entity = null;
						previousValue.Pago.Remove(this);
					}
					this._EstadoPago.Entity = value;
					if ((value != null))
					{
						value.Pago.Add(this);
						this._IdEstadoP = value.IdEstadoP;
					}
					else
					{
						this._IdEstadoP = default(int);
					}
					this.SendPropertyChanged("EstadoPago");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="EstudianteInscrito_Pago", Storage="_EstudianteInscrito", ThisKey="IdEstInsc", OtherKey="IdEstInsc", IsForeignKey=true)]
		public EstudianteInscrito EstudianteInscrito
		{
			get
			{
				return this._EstudianteInscrito.Entity;
			}
			set
			{
				EstudianteInscrito previousValue = this._EstudianteInscrito.Entity;
				if (((previousValue != value) 
							|| (this._EstudianteInscrito.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._EstudianteInscrito.Entity = null;
						previousValue.Pago.Remove(this);
					}
					this._EstudianteInscrito.Entity = value;
					if ((value != null))
					{
						value.Pago.Add(this);
						this._IdEstInsc = value.IdEstInsc;
					}
					else
					{
						this._IdEstInsc = default(int);
					}
					this.SendPropertyChanged("EstudianteInscrito");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Persona")]
	public partial class Persona : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdPersona;
		
		private string _CI;
		
		private string _Nombres;
		
		private string _ApPat;
		
		private string _ApMat;
		
		private System.DateTime _FechaNac;
		
		private System.Nullable<int> _IdBeca;
		
		private EntitySet<Usuario> _Usuario;
		
		private EntitySet<EstudianteInscrito> _EstudianteInscrito;
		
		private EntitySet<ModuloImpartido> _ModuloImpartido;
		
		private EntityRef<Beca> _Beca;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdPersonaChanging(int value);
    partial void OnIdPersonaChanged();
    partial void OnCIChanging(string value);
    partial void OnCIChanged();
    partial void OnNombresChanging(string value);
    partial void OnNombresChanged();
    partial void OnApPatChanging(string value);
    partial void OnApPatChanged();
    partial void OnApMatChanging(string value);
    partial void OnApMatChanged();
    partial void OnFechaNacChanging(System.DateTime value);
    partial void OnFechaNacChanged();
    partial void OnIdBecaChanging(System.Nullable<int> value);
    partial void OnIdBecaChanged();
    #endregion
		
		public Persona()
		{
			this._Usuario = new EntitySet<Usuario>(new Action<Usuario>(this.attach_Usuario), new Action<Usuario>(this.detach_Usuario));
			this._EstudianteInscrito = new EntitySet<EstudianteInscrito>(new Action<EstudianteInscrito>(this.attach_EstudianteInscrito), new Action<EstudianteInscrito>(this.detach_EstudianteInscrito));
			this._ModuloImpartido = new EntitySet<ModuloImpartido>(new Action<ModuloImpartido>(this.attach_ModuloImpartido), new Action<ModuloImpartido>(this.detach_ModuloImpartido));
			this._Beca = default(EntityRef<Beca>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPersona", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdPersona
		{
			get
			{
				return this._IdPersona;
			}
			set
			{
				if ((this._IdPersona != value))
				{
					this.OnIdPersonaChanging(value);
					this.SendPropertyChanging();
					this._IdPersona = value;
					this.SendPropertyChanged("IdPersona");
					this.OnIdPersonaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CI", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CI
		{
			get
			{
				return this._CI;
			}
			set
			{
				if ((this._CI != value))
				{
					this.OnCIChanging(value);
					this.SendPropertyChanging();
					this._CI = value;
					this.SendPropertyChanged("CI");
					this.OnCIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombres", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombres
		{
			get
			{
				return this._Nombres;
			}
			set
			{
				if ((this._Nombres != value))
				{
					this.OnNombresChanging(value);
					this.SendPropertyChanging();
					this._Nombres = value;
					this.SendPropertyChanged("Nombres");
					this.OnNombresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApPat", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ApPat
		{
			get
			{
				return this._ApPat;
			}
			set
			{
				if ((this._ApPat != value))
				{
					this.OnApPatChanging(value);
					this.SendPropertyChanging();
					this._ApPat = value;
					this.SendPropertyChanged("ApPat");
					this.OnApPatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApMat", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ApMat
		{
			get
			{
				return this._ApMat;
			}
			set
			{
				if ((this._ApMat != value))
				{
					this.OnApMatChanging(value);
					this.SendPropertyChanging();
					this._ApMat = value;
					this.SendPropertyChanged("ApMat");
					this.OnApMatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaNac", DbType="Date NOT NULL")]
		public System.DateTime FechaNac
		{
			get
			{
				return this._FechaNac;
			}
			set
			{
				if ((this._FechaNac != value))
				{
					this.OnFechaNacChanging(value);
					this.SendPropertyChanging();
					this._FechaNac = value;
					this.SendPropertyChanged("FechaNac");
					this.OnFechaNacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdBeca", DbType="Int")]
		public System.Nullable<int> IdBeca
		{
			get
			{
				return this._IdBeca;
			}
			set
			{
				if ((this._IdBeca != value))
				{
					if (this._Beca.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdBecaChanging(value);
					this.SendPropertyChanging();
					this._IdBeca = value;
					this.SendPropertyChanged("IdBeca");
					this.OnIdBecaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Persona_Usuario", Storage="_Usuario", ThisKey="IdPersona", OtherKey="IdPersona")]
		public EntitySet<Usuario> Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				this._Usuario.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Persona_EstudianteInscrito", Storage="_EstudianteInscrito", ThisKey="IdPersona", OtherKey="IdPersona")]
		public EntitySet<EstudianteInscrito> EstudianteInscrito
		{
			get
			{
				return this._EstudianteInscrito;
			}
			set
			{
				this._EstudianteInscrito.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Persona_ModuloImpartido", Storage="_ModuloImpartido", ThisKey="IdPersona", OtherKey="IdPersona")]
		public EntitySet<ModuloImpartido> ModuloImpartido
		{
			get
			{
				return this._ModuloImpartido;
			}
			set
			{
				this._ModuloImpartido.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Beca_Persona", Storage="_Beca", ThisKey="IdBeca", OtherKey="IdBeca", IsForeignKey=true)]
		public Beca Beca
		{
			get
			{
				return this._Beca.Entity;
			}
			set
			{
				Beca previousValue = this._Beca.Entity;
				if (((previousValue != value) 
							|| (this._Beca.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Beca.Entity = null;
						previousValue.Persona.Remove(this);
					}
					this._Beca.Entity = value;
					if ((value != null))
					{
						value.Persona.Add(this);
						this._IdBeca = value.IdBeca;
					}
					else
					{
						this._IdBeca = default(Nullable<int>);
					}
					this.SendPropertyChanged("Beca");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Usuario(Usuario entity)
		{
			this.SendPropertyChanging();
			entity.Persona = this;
		}
		
		private void detach_Usuario(Usuario entity)
		{
			this.SendPropertyChanging();
			entity.Persona = null;
		}
		
		private void attach_EstudianteInscrito(EstudianteInscrito entity)
		{
			this.SendPropertyChanging();
			entity.Persona = this;
		}
		
		private void detach_EstudianteInscrito(EstudianteInscrito entity)
		{
			this.SendPropertyChanging();
			entity.Persona = null;
		}
		
		private void attach_ModuloImpartido(ModuloImpartido entity)
		{
			this.SendPropertyChanging();
			entity.Persona = this;
		}
		
		private void detach_ModuloImpartido(ModuloImpartido entity)
		{
			this.SendPropertyChanging();
			entity.Persona = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Rol")]
	public partial class Rol : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdRol;
		
		private string _Nombre;
		
		private EntitySet<Usuario> _Usuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdRolChanging(int value);
    partial void OnIdRolChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    #endregion
		
		public Rol()
		{
			this._Usuario = new EntitySet<Usuario>(new Action<Usuario>(this.attach_Usuario), new Action<Usuario>(this.detach_Usuario));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdRol", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdRol
		{
			get
			{
				return this._IdRol;
			}
			set
			{
				if ((this._IdRol != value))
				{
					this.OnIdRolChanging(value);
					this.SendPropertyChanging();
					this._IdRol = value;
					this.SendPropertyChanged("IdRol");
					this.OnIdRolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Rol_Usuario", Storage="_Usuario", ThisKey="IdRol", OtherKey="IdRol")]
		public EntitySet<Usuario> Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				this._Usuario.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Usuario(Usuario entity)
		{
			this.SendPropertyChanging();
			entity.Rol = this;
		}
		
		private void detach_Usuario(Usuario entity)
		{
			this.SendPropertyChanging();
			entity.Rol = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sucursal")]
	public partial class Sucursal : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdSucursal;
		
		private string _Alias;
		
		private string _Ubicacion;
		
		private string _TelefonoContacto;
		
		private EntitySet<Aula> _Aula;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdSucursalChanging(int value);
    partial void OnIdSucursalChanged();
    partial void OnAliasChanging(string value);
    partial void OnAliasChanged();
    partial void OnUbicacionChanging(string value);
    partial void OnUbicacionChanged();
    partial void OnTelefonoContactoChanging(string value);
    partial void OnTelefonoContactoChanged();
    #endregion
		
		public Sucursal()
		{
			this._Aula = new EntitySet<Aula>(new Action<Aula>(this.attach_Aula), new Action<Aula>(this.detach_Aula));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdSucursal", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdSucursal
		{
			get
			{
				return this._IdSucursal;
			}
			set
			{
				if ((this._IdSucursal != value))
				{
					this.OnIdSucursalChanging(value);
					this.SendPropertyChanging();
					this._IdSucursal = value;
					this.SendPropertyChanged("IdSucursal");
					this.OnIdSucursalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alias", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Alias
		{
			get
			{
				return this._Alias;
			}
			set
			{
				if ((this._Alias != value))
				{
					this.OnAliasChanging(value);
					this.SendPropertyChanging();
					this._Alias = value;
					this.SendPropertyChanged("Alias");
					this.OnAliasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ubicacion", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Ubicacion
		{
			get
			{
				return this._Ubicacion;
			}
			set
			{
				if ((this._Ubicacion != value))
				{
					this.OnUbicacionChanging(value);
					this.SendPropertyChanging();
					this._Ubicacion = value;
					this.SendPropertyChanged("Ubicacion");
					this.OnUbicacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelefonoContacto", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string TelefonoContacto
		{
			get
			{
				return this._TelefonoContacto;
			}
			set
			{
				if ((this._TelefonoContacto != value))
				{
					this.OnTelefonoContactoChanging(value);
					this.SendPropertyChanging();
					this._TelefonoContacto = value;
					this.SendPropertyChanged("TelefonoContacto");
					this.OnTelefonoContactoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Sucursal_Aula", Storage="_Aula", ThisKey="IdSucursal", OtherKey="IdSucursal")]
		public EntitySet<Aula> Aula
		{
			get
			{
				return this._Aula;
			}
			set
			{
				this._Aula.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Aula(Aula entity)
		{
			this.SendPropertyChanging();
			entity.Sucursal = this;
		}
		
		private void detach_Aula(Aula entity)
		{
			this.SendPropertyChanging();
			entity.Sucursal = null;
		}
	}
}
#pragma warning restore 1591
